- packages/embed/src/validation.ts
Updates validation rule for `amount` value so that we allow all non-negative numbers.
> fix: allow zero value auth transactions

- packages/embed/__mocks__/styleMock.ts
- packages/embed/node/index.js
- packages/embed/package.json
- packages/embed/src/overlay/overlay.ts
- packages/embed/src/skeleton/skeleton.ts
- packages/embed/src/ssr.test.ts
SSR has issues with webpack `style-loader` as the `document` is not present in a node environment.
This is due to the styles being injected to the document.
I have added a test that runs in the `node` environment specifically to check this (I removed the previous one as it was done on the build, not whilst running `yarn test`). `styleMock` will throw an exception if document is undefined - we should not be loading and styles unless we have a DOM :-)
There might be a better of solving this in terms of how we load styles onto the merchants page.
> fix: Resolves SSR issues when using with Next

- cloudbuild/cloudbuild-cdn.yaml
- cloudbuild/deploy.yaml
Adding two Cloud Build config files.
- `cloudbuild-cdn.yaml` to build and move the embed-cdn `gr4vy-embed.js` file to a storage bucket.
- `deploy.yaml` to be used by our deployment process copy the required file from storage and into the Gr4vy instance being deployed to.
> Add cloud build configs

- packages/embed/src/validation.ts
A small issue with the `gr4vyId` and `apiHost`/`iframeHost`.
We are now validating the user input before creating the config which broke this.
This fix ensures we allow for either gr4vyId or hosts
> fix: embed validation

- .github/workflows/ci.yml
Add a Trivy GitHub Action job to scan for vulnerabilities. This alerts us to vulnerable packages sooner.
> Add Trivy GitHub action job

- packages/embed/package.json
- packages/embed/src/apple-pay/apple-pay.test.ts
- packages/embed/src/apple-pay/apple-pay.ts
- packages/embed/src/apple-pay/browser-support.test.ts
- packages/embed/src/apple-pay/browser-support.ts
- packages/embed/src/apple-pay/index.ts
- packages/embed/src/index.ts
- packages/embed/src/subjects.ts
- packages/embed/src/types.ts
- yarn.lock
Add support for Apple Pay - also detects the version of the API being used and attempts to upgrade to version 5 (broadest set of card schemes), but at a minimum fallbacks to 3 (pre 3 has a subtly different api).
> feat: add apple pay support

- packages/embed/src/apple-pay/apple-pay.test.ts
- packages/embed/src/apple-pay/apple-pay.ts
- packages/embed/src/index.ts
- packages/embed/src/subjects.ts
- packages/embed/src/utils/create-subject.ts
Resolves issues around cancellation of the Apple Pay payment sheet.
Dismissing Apple Pay previously left the checkout in a pending state when the user dismissed the payment sheet. This also resolves the issue of the transaction being completed before the payment sheet has closed.
> Resolves issues cancelling Apple Pay

- packages/embed/src/apple-pay/apple-pay.test.ts
- packages/embed/src/form/form.test.ts
- packages/embed/src/frame/frame.test.ts
- packages/embed/src/overlay/overlay.test.ts
- packages/embed/src/popup/popup.test.ts
- packages/embed/src/skeleton/skeleton.test.ts
- packages/embed/src/subjects.test.ts
- packages/embed/src/utils/create-subject.ts
This was incorrect. (Albeit it had no effect). This wasn't doing the callback in a separate macro-task.
With it actually working - It meant a few tests needed to be updated to flush the macro-task queue with `jest.runAllTimers();` See https://jestjs.io/docs/timer-mocks#run-all-timers
**Before**
```subscribers.forEach((callbackFn) => setTimeout(callbackFn(value), 0))```
**After**
```
subscribers.forEach((callbackFn) => {
setTimeout(callbackFn(value), 0)
})
```
> fix: update async tests

- packages/embed-react/src/index.stories.tsx
- packages/embed/src/index.ts
- packages/embed/src/types.ts
- packages/embed/src/validation.ts
This is no longer used (mainly for internal development). This was never documented as something that you could do in Embed so marking it as an internal/minor change.
> refactor: remove prefer response

- package.json
- packages/embed-react/README.md
- packages/embed/README.md
- packages/embed/src/form/form.test.ts
- packages/embed/src/form/form.ts
- packages/embed/src/index.ts
- packages/embed/src/subjects.ts
- packages/embed/src/types.ts
- yarn.lock
Allows you to add custom options to Embed that will be processed outside of Gr4vy.
```tsx
<Gr4vyEmbed
// Provide a list of custom options
customOptions={[
{
label: 'Giftcard',
method: 'giftcard',
description: 'You will be asked to enter a giftcard',
iconUrl: `data:image/svg+xml,...`,
}
]}
// Handle the submit for a custom option
onCustomSubmit={({ method: 'giftcard' }) => {
alert(`Paid by ${method}`);
}}
/>
```
> feat: add custom options

- packages/embed-react/package.json
- packages/embed-react/src/Gr4vyEmbed.tsx
- packages/embed-react/src/index.stories.tsx
Adds memoization for prop-changes - React will do a shallow compare, but this does a deep comparison to see whats changed. We could optimise later on to just pass-through changes.
Embed React will now re-render on prop changes. This uses React `memo` with a deep comparison of props so nested objects, such as `theme` will still cause a re-render if changed.
> fix: embed does not re-render when props change

- packages/embed/src/types.ts
Adds support for theming radio inputs using `inputRadioBorder` and `inputRadioBorderChecked`, if these are not defined the previous default values will be used (no visual breaking changes).
> Radio input theme support

- packages/embed-react/README.md
- packages/embed/README.md
- packages/embed/src/index.ts
- packages/embed/src/types.ts
Passes through the `transactionFailed` events to `onEvent` - It's not super clear what all the possible return error types are from https://gr4vy.com/docs/reference#operation/authorize-new-transaction
💡 We could potentially look at using `type import` https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html and get these values from the SDK in future.
> Support for transactionFailed event when using onEvent

- yarn.lock
Update `http-server` to fetch latest `follow-redirects` release.
> chore: CVE-2022-0155

- cloudbuild/cloudbuild-cdn.yaml
The Cloud Build step to deploy the service always uses the [`main` reference](https://github.com/gr4vy/gr4vy-embed/blob/c9599e7dafe2f4ed471534b20fa4b498b0358565/cloudbuild/cloudbuild-cdn.yaml#L95) when calling the GitHub deployment API.
We recently saw a number of service deployments to `spider` fail because the container couldn't be found. This happened because there had been another commit to the main branch before the request to the GitHub deployment API was made.
This PR changes the request to the GitHub deployment API to use the commit SHA as the reference, ensuring we deploy the container built in the previous step.
> deploy commit sha [skip ci]

- cloudbuild/deploy-env.yaml
Amending the deployment step related to cache invalidation to prepare for the introduction of a shared HTTPS load balancer.
The command to invalidate the cache on the new load balancer will not fail the deployment if it’s unable to complete, allowing us to introduce the new shared load balancers without interrupting deployments.
> Deploy during shared LB migration [PE-128]

- cloudbuild/deploy-env.yaml
Amending the deployment step related to cache invalidation on the new shared HTTPS load balancer. Removes reference to the old load balancer that no longer exists.
> Deployment -  invalidate cache on shared lb only

- .trivyignore
- package.json
- packages/embed/src/create-config.test.ts
- packages/embed/src/create-config.ts
- packages/embed/src/index.ts
- packages/embed/src/utils/pick.test.ts
- packages/embed/src/utils/pick.ts
- yarn.lock
**Description:** Adds `gr4vyId` to the options object passed to the embed, for debugging purposes.
**Ticket:** https://gr4vy.atlassian.net/browse/TA-1026
**Screenshot(s):**
> feat: explicitly log authentication errors as warnings

- yarn.lock
Upgrades `async` dependency from 2.6.3 to 2.6.4 to fix trivy warning.
> chore: upgrade async 2.6.4

- cloudbuild/cloudbuild-cdn.yaml
The Cloud Build step "" was always compressing and uploading the `node_modules` directory, even when the `yarn.lock` file hadn't changed.
```
gcr.io/gr4vy-admin/save_cache:latest
CommandException: One or more URLs matched no objects.
Compressing cache to ./node_modules-2636734882.tgz...
Uploading cache to Google Cloud Storage...
Copying file://./node_modules-2636734882.tgz [Content-Type=application/x-tar]...
/ [0 files][    0.0 B/  2.3 GiB]                                                
Operation completed over 1 objects/2.3 GiB.
```
The check that the save_cache builder does already adds a slash when constructing the gsutil command to run:
https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/cache/save_cache#L78
This meant that we were searching for an object with …
> Fix "save cache" Cloud Build step [PE-219]

- packages/embed/src/utils/version.ts
**Description:** When using the cdn version of embed, there's a `window.gr4vy` object already but `version` is not defined, causing an error when trying to set the version from there. This fixes it.
> Fix window.gr4vy.version declaration

- packages/embed/src/utils/version.ts
**Description:** We pushed a hotfix https://github.com/gr4vy/gr4vy-embed/pull/86 for a production error, but the `embed` version stopped displaying. This fixes it, and makes sure that error doesn't surface anymore. Tested with both `embed/react` and `embed/cdn`
**Ticket:** https://gr4vy.atlassian.net/browse/TA-1466
> fix: embed version doesn't display anymore

- packages/embed/src/frame/frame.test.ts
- packages/embed/src/frame/frame.ts
- packages/embed/src/overlay/overlay.ts
**Description:** Fixes an issue where Google Pay might not get launched properly on browsers other than Chrome (Brave, Firefox..), due to restrictions we recently added to our iframes.
**Ticket:** https://gr4vy.atlassian.net/browse/TA-1687
<details>
<summary>📦 Published PR as canary version: <code>2.11.5--canary.89.056cbba.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @gr4vy/embed-react@2.11.5--canary.89.056cbba.0
npm install @gr4vy/embed@2.11.5--canary.89.056cbba.0
yarn add @gr4vy/embed-react@2.11.5--canary.89.056cbba.0
yarn add @gr4vy/embed@2.11.5--canary.89.056cbba.0
```
</details>
> Add allow-popups and allow-top-navigation to sandboxed iframe

- packages/embed/src/popup/popup.test.ts
- packages/embed/src/popup/popup.ts
- packages/embed/src/subjects.ts
- packages/embed/webpack.dev.js
Adds popup dimension configuration or fallback to standard size.
Adds the capability for popup redirects to have a custom size set by individual payment processors.
> add approval ui dimensions

- packages/example-cdn/index.test.ts
- packages/example-cdn/package.json
- packages/example-cdn/playwright.config.ts
- yarn.lock
Adds a basic playwright test that loads up the CDN build of the project and does a mocked handshake with Embed. This is focused on resolving TA-1722 (but we might use/adapt later as wider testing strategy).
This is the test in CI:
This is the test with the debugger:
Fixes # (issue)
> test: add test for embed cdn

- .trivyignore
- cloudbuild/cloudbuild-cdn.yaml
There's a new version of the [`deployer`](https://github.com/gr4vy/deployer) tool which changes the command used to create a new deployment for a service.
This PR updates the command used in `cloudbuild.yaml` to be compatible with the latest verison of the deployer tool.
<sub>This PR was generated using [turbolift](https://github.com/Skyscanner/turbolift).</sub>
> Update `deployer` command

- packages/embed/src/index.ts
- packages/embed/src/types.ts
Related to https://github.com/gr4vy/embed-ui/pull/376. This adds a `scrollTo` listener for handling scrolling-to-element interactions in Embed
> Add scrollTo listener

- cloudbuild/deploy-env.yaml
A new Storage bucket has been created with a different naming convention and PR https://github.com/gr4vy/gr4vy-embed/pull/109 added an extra deployment step to deploy the `gr4vy-embed` code into this new bucket as well as the old bucket.
Now that our traffic has been migrated to the new bucket this PR removes the extra step and only deploys to the new bucket.
Fixes # PE-188
> [PE-188] Remove deploy step for old storage bucket

- packages/embed/src/popup/popup.test.ts
- packages/embed/src/popup/popup.ts
Changes the behaviour of popups so that clicking "Re-open window" on the overlay refocuses an existing popup instead of opening a new one. If there's no existing popup, it will open a new one as usual.
Fixes TA-2948
> feat: refocus redirect popup

- packages/embed/src/overlay/overlay.test.ts
- packages/embed/src/overlay/overlay.ts
Adds a listener for `beforeunload` once a redirect popup is open, prompting the user to either cancel or leave the site if the window/tab is closed or reloaded. Removes the listener if the popup closes.
Fixes TA-732
> feat: close popup before unload

- .trivyignore
Add CVE-2022-37603, and CVE-2022-37599 to `.trivyignore`.
> chore: add CVE-2022-37603 and CVE-2022-37599 to trivyignore

- .github/workflows/escrow.yml
We'd like to support a software escrow agreement and need a backup of our source code.
> Software Escrow is a three party agreement between a software developer (Gr4vy), the end user and the source code escrow company. The objective of a software escrow agreement is to provide comfort to the end user that if the software developer is unable or unwilling to support the software, the code, data and other critical materials can be released to them.
This PR creates a scheduled GitHub Action to add all files within this repo to a compressed archive, and then to encrypt the archive with AES256 symmetric encryption. The encrypted archive is then commited to another repo, [`gr4vy/software-escrow`](https://github.com/gr4vy/software-escrow) where the software escrow company can connected, download, …
> Add Software Escrow GitHub Action

- package.json
- yarn.lock
> chore(dev-deps): bump html-webpack-plugin from 4.5.0 to 5.5.0

- packages/embed/src/index.ts
- packages/embed/src/popup/popup.ts
- packages/embed/src/subjects.ts
- packages/embed/src/types.ts
Fix TransactionFailed event triggering when editing billing details in embed
https://gr4vy.atlassian.net/browse/TA-4145
Embed UI PR: [embed-ui/pull/684](https://github.com/gr4vy/embed-ui/pull/684)
> fix: TransactionFailed event triggering when editing billing details

- package.json
- packages/embed-react/webpack.dev.js
- packages/embed/webpack.dev.js
- yarn.lock
I updated `webpack-cli` as there was issue with `trivy` on google cloud build. But [webpack-cli](https://github.com/webpack/webpack-cli/releases/tag/webpack-cli%405.0.0) no longer supports `webpack-dev-server` v3, the minimum supported version is `webpack-dev-server` v4.0.0.
So I updated `webpack-dev-server` and config according [migration guide](https://github.com/webpack/webpack-dev-server/blob/0002ebfbc8f36e92f91013372c9e2bca97022825/migration-v4.md)
> fix: webpack dev server

- .trivyignore
Add trivy vulnerability to ignore list
https://github.com/gr4vy/gr4vy-embed/actions/runs/4794544117/jobs/8528041162
I added tags `release` and `patch` as [previous PR](https://github.com/gr4vy/gr4vy-embed/pull/143) was not deployed:
https://console.cloud.google.com/cloud-build/builds;region=global/0d57cdc3-6479-4b9d-8794-1b2e566c0d4e?authuser=1&project=gr4vy-admin
> fix: trivy vulnerability

- cloudbuild/cloudbuild-cdn.yaml
This change simply attaches the [`deployer`](https://github.com/gr4vy/deployer) container to the cloudbuild network so that we have access to the Cloud Build Service Account credentials for future use.
We're in the process of adding a new features to our [`deployer`](https://github.com/gr4vy/deployer) tool. Some of these new feature will require access to Google Cloud APIs. At the moment the Docker command we use to execute the `deployer` tool doesn't attach the container to the cloudbuild network, which is required to access the Cloud Build service account's credentials:
https://cloud.google.com/build/docs/build-config-file-schema#network
> When Cloud Build runs each build step, it attaches the step's container to a local Docker network named cloudbuild. The cloudbuild network hosts …
> build: run the `deployer` tool on the cloudbuild network

- cloudbuild/deploy-env.yaml
Add a label to the storage bucket that serves embed-ui to show the commit sha of the code deployed in the bucket.
> Add commit sha label to bucket when deploying

- .trivyignore
- yarn.lock
Fix trivy warnings by upgraded deps. Added dev dependencies to ignore file (we need to upgrade to the latest version of jest which is a little more involved).
> chore: upgrade/check dependencies

- cloudbuild/cloudbuild-cdn.yaml
- cloudbuild/deploy-env.yaml
Google Cloud Build switched from `e2-medium` to `e2-standard-2` machine type as the default instance size for Cloud Build jobs where `machineType` is undefined.
https://cloud.google.com/build/docs/release-notes#September_01_2023
Most of our Cloud Build configs leave the machine type undefined, meaning we’re now using the larger, more expensive instance. We’ve seen our monthly cost for Cloud Build grow from $0.28/minute (Aug) to $0.57/minute (Sept) with no meaningful improvement in build times.
This PR sets `machineType: 'e2-medium'` where it's currently undefined.
<sub>This PR was generated using [turbolift](https://github.com/Skyscanner/turbolift).</sub>
> Cloud Build machineType

- packages/embed/src/apple-pay/apple-pay.ts
- packages/embed/src/index.ts
- packages/embed/src/subjects.ts
Captures error messages for failing to start an Apple Pay session.
> chore(apple-pay): add error message to apple pay session failure

- package.json
- yarn.lock
Resolve the `parse-url` version to later version - This is used by Lerna (which builds locally, will need to run through release) and should not affect the bundle.
> deps: fix version of parse-url

- .github/dependabot.yml
Renovate currently doesn't create PRs for vulnerabilities that only exist in transitive dependencies. There's a `transitiveRemediation` flag that can be used, but it only seems to support npm (or doesn't fully work atm).
The alternative would be to add `:maintainLockFilesMonthly` and let Renovate create a PR to update the lockfile monthly (can be set to weekly too), covering any vulnerability but it sounds messy.
This PR adds back dependabot and tell it to only create those vulnerability PRs, complementing renovate.
> Re-add dependabot to handle transitive dependencies vulnerabilities

- .trivyignore
- package.json
- yarn.lock
Add resolution to tar `^6.2.1`, fixing the vulnerability related to it https://github.com/gr4vy/gr4vy-embed/security/dependabot/70.
This package is used by the main dependency `lerna`. It looks like the new `8` version will fix this but upgrading that will be covered in a separate ticket https://gr4vy.atlassian.net/browse/TA-6352. Here we're using yarn resolutions to resolve the specific minor version containing the fix.
- `gr4vy-admin` build https://console.cloud.google.com/cloud-build/builds;region=global/8447e46f-6f5e-4044-af1d-eeca017cde88?project=gr4vy-admin ✅ 
- `spider` build https://console.cloud.google.com/cloud-build/builds;region=global/b59d4d9e-91c1-4f75-8c1f-1cb97cf6314d?project=spider-ef8f ✅ 
see …
> fix: update insecure tar dependency

- package.json
- packages/embed/src/types.ts
- yarn.lock
We did this a while ago https://github.com/gr4vy/gr4vy-embed/pull/46 but the type wasn't updated
> chore: make form prop option type optional

- .trivyignore
- cloudbuild/deploy-env.yaml
Google Cloud Build automatically selects the default Cloud Build service account to execute builds on your behalf, unless you override this behavior. This default service account may have permissions that are unnecessarily broad.
Google are changing the default behavior for how Cloud Build uses service accounts in new projects. These changes will improve the default security posture going forward.
[Announcement](https://cloud.google.com/build/docs/cloud-build-service-account-updates)
To continue to use Google Cloud Build for Gr4vy service deployments we need to begin specifying a service account to execute the Cloud Build and define the logging options.
[Configure user-specified service accounts](https://cloud.google.com/build/docs/securing-builds/configure-user-specified-service-accounts) …
> Execute service deployment with a user-defined service account

- packages/embed/src/index.ts
- packages/embed/src/theme/create-theme.ts
- packages/embed/src/types.ts
- packages/embed/src/validation.test.ts
- packages/embed/src/validation.ts
As part of the new [Guest Checkout](https://gr4vy.atlassian.net/browse/TA-6580) feature we want to add support for a `buyer` option merchants can use with optional billing and shipping details. This PR does that and also extends validation to make sure integrations don't pass a combination of buyer values or a malformed `buyer` object.
Not using anything fancy like `zod` as I didn't want to add an external library.
**Ticket:** https://gr4vy.atlassian.net/browse/TA-7917
**Screenshots:**
> task: add support for buyer option

- .github/workflows/ci.yml
- cloudbuild/cloudbuild-cdn.yaml
Jira: [PE-860](https://gr4vy.atlassian.net/browse/PE-860)
Trivy scans the source code and any container image for vulnerabilities. However, when using the default repository for the trivy database, we see rate limiting issues:
```
Fatal error	init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
* GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 669.3µs, allowed: 44000/minute
```
This has been widely reported on the Trivy git repositories and the Trivy maintainers are making changes in an attempt to improve the situation. However it's unclear how long these changes will take and it appears the changes will only be available in the latest versions. We often pin to an older version …
> trivy-db repository

- packages/embed-react/src/index.stories.tsx
- packages/embed/src/types.ts
- packages/embed/src/validation.test.ts
- packages/embed/src/validation.ts
This was removed [a while ago](https://github.com/gr4vy/gr4vy-embed/pull/19) from the docs, but not from the types and validation logic. We don't have it in `core-api`.
> chore: remove unused `approve` intent from types and validation

- package.json
- yarn.lock
Resolves `path-to-regexp` dependency to version 0.1.12
Fixes https://github.com/gr4vy/gr4vy-embed/security/dependabot/86
> fix: path-to-regexp vulnerability

- cloudbuild/cloudbuild-cdn.yaml
Adding tags to the Cloud Build config files to better identify what Cloud Build is being used for and to filer data to visualise build metrics.
<sub>This PR was generated using [turbolift](https://github.com/Skyscanner/turbolift).</sub>
> Cloud Build tags

- .github/workflows/ci.yml
- packages/embed/src/index.ts
Adds a warning log if Embed is submitted more than once in quick succession so that merchants are aware of potential issues related to a double submission (mainly wallets creating two sessions and throwing `Page already has an active payment session.`)
**Ticket:** https://gr4vy.atlassian.net/browse/TA-10323
**Screenshots:**
> task: add warning log for double submissions

- packages/embed-react/README.md
- packages/embed/README.md
- packages/embed/src/index.ts
Exposes the new `cardDetailsChanged` event to `onEvent` so merchants can subscribe to it.
Depends on https://github.com/gr4vy/embed-ui/pull/1296
**Ticket:** https://gr4vy.atlassian.net/browse/TA-12022?atlOrigin=eyJpIjoiYTNjYTY3YzE2YzViNDZhN2JkOGFhNjI3MGMxY2E3ZDQiLCJwIjoiaiJ9
**Screenshots:**
> task: expose cardDetailsChanged event to onEvent handler
