- packages/embed/src/emitter/emitter.test.ts
- packages/embed/src/emitter/emitter.ts
- packages/embed/src/overlay/overlay.test.ts
- packages/embed/src/overlay/overlay.ts
- packages/embed/src/popup/popup.test.ts
- packages/embed/src/popup/popup.ts
- packages/embed/src/popup/redirect-document.ts
- packages/embed/src/subjects.test.ts
- packages/embed/src/subjects.ts
- Adds support for translations from embed-ui via the `modeUpdated` event
- Remove concept of approval required - its now based on whether mode has a popup in its configuration.
> feat: adding support for popup/overlay locale from embed-ui

- package.json
<details>
<summary>📦 Published PR as canary version: <code>1.3.6--canary.14.93cf65a454e3091b6b937788fa09d8ecc6ded27a.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @gr4vy/embed-react@1.3.6--canary.14.93cf65a454e3091b6b937788fa09d8ecc6ded27a.0
npm install @gr4vy/embed@1.3.6--canary.14.93cf65a454e3091b6b937788fa09d8ecc6ded27a.0
yarn add @gr4vy/embed-react@1.3.6--canary.14.93cf65a454e3091b6b937788fa09d8ecc6ded27a.0
yarn add @gr4vy/embed@1.3.6--canary.14.93cf65a454e3091b6b937788fa09d8ecc6ded27a.0
```
</details>
> add author

- .trivyignore
Add a `.trivyignore` file which contains a list of vulnerability IDs to be ignored by [Trivy](https://aquasecurity.github.io/trivy/v0.19.2/) vulnerability scanning.
Example usage [here](https://aquasecurity.github.io/trivy/v0.19.2/vulnerability/examples/filter/#by-vulnerability-ids).
> Add .trivyignore file

- packages/embed-react/src/__snapshots__/storyshots.test.ts.snap
- packages/embed-react/src/index.stories.tsx
- yarn.lock
Upgrading dependencies, there are now 11 issues left down from 32.
Also noticed React storybook was not working correctly - this ensures we actually pass in a valid form reference.
> Upgrade dependencies

- packages/embed-react/README.md
- packages/embed/README.md
- packages/embed/dev/index.ts
- packages/embed/src/index.ts
- packages/embed/src/types.ts
- packages/embed/src/validation.ts
Adds support for pass-through metadata.
> feat: add metadata support

- packages/embed-react/README.md
- packages/embed-react/src/Gr4vyEmbed.tsx
- packages/embed-react/src/index.stories.tsx
- packages/embed-react/src/index.ts
- packages/embed/README.md
- packages/embed/src/index.test.ts
- packages/embed/src/index.ts
- packages/embed/src/subjects.ts
- packages/embed/src/submit/index.ts
- packages/embed/src/submit/submit.test.ts
- packages/embed/src/submit/submit.ts
- packages/embed/src/types.ts
Removes the required 'form' prop so that Embed can be used without a form.
> feat: support for optional form

- packages/embed-react/README.md
- packages/embed/README.md
- packages/embed/src/index.ts
- packages/embed/src/types.ts
- packages/embed/src/validation.ts
Adds support for passing an array of cart items via embed.
> feat(cart items): add support for cart items pass through [TA-458]

- package.json
- packages/embed/src/index.ts
- packages/embed/src/overlay/overlay.ts
- packages/embed/src/subjects.ts
- packages/embed/src/types.ts
- yarn.lock
On receiving a void overlay via the modeUpdate IPC the overlay will be closed.
> Show the loading state for Google Pay

- .github/workflows/ci.yml
Enables manual workflow runs via the GitHub UI on the main branch: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
NOTE: The run-flow button should will only be visible in the main branch's Actions section
> task: enable manual workflow runs

- packages/embed/src/index.ts
- packages/embed/src/types.ts
Merging Billing Details Revamp UI bucket into main, as this change won't do anything until the work on `embed-ui` is done, so it's safe.
> Add scrollTo listener (#105)

- .github/workflows/ci.yml
- package.json
- packages/embed/dev/index.ts
- yarn.lock
Adds ability to set a Gr4vy ID as the environment variable.
> chore: add gr4vy id as env variable

- .eslintrc.js
- .vscode/settings.json
- package.json
- packages/embed-react/.eslintrc.js
- packages/embed-react/tsconfig.json
- packages/embed-react/webpack.dev.js
- packages/embed/.eslintrc.js
- packages/embed/jest.config.js
- packages/embed/package.json
- packages/embed/src/apple-pay/apple-pay.test.ts
- packages/embed/src/apple-pay/apple-pay.ts
- packages/embed/src/form/form.test.ts
- packages/embed/src/form/form.ts
- packages/embed/src/frame/frame.test.ts
- packages/embed/src/frame/frame.ts
- packages/embed/src/overlay/overlay.test.ts
- packages/embed/src/overlay/overlay.ts
- packages/embed/src/popup/popup.test.ts
- packages/embed/src/popup/popup.ts
- packages/embed/src/skeleton/skeleton.test.ts
- packages/embed/src/skeleton/skeleton.ts
- packages/embed/src/submit/submit.test.ts
- packages/embed/src/submit/submit.ts
- packages/embed/tsconfig.json
- packages/embed/webpack.dev.js
- packages/embed/webpack.prod.js
- yarn.lock
**Ticket: [TA-2936 [Embed] Set up absolute imports and replace relative paths](https://gr4vy.atlassian.net/browse/TA-2936)**
> chore: absolute imports (embed)

- packages/embed-react/src/Gr4vyEmbed.tsx
It fixes the following error shown on the terminal when running in dev mode:
<sub>**Reference link:** https://github.com/gr4vy/gr4vy-embed/pull/117#issuecomment-1331831912</sub>
> fix: dev mode terminal error

- packages/embed/src/index.ts
- packages/embed/src/validation.test.ts
- packages/embed/src/validation.ts
Checks a function is provided for the `onBeforeTransaction`
Fixes # (issue)
> feat: add check for function onBeforeTransaction

- package.json
- yarn.lock
Upgrades webpack to fix a vulnerability.
> chore: upgrade webpack

- .github/workflows/ci.yml
Before:
After:
Fixes # [TA-2332](https://gr4vy.atlassian.net/browse/TA-2332)
[TA-2332]: https://gr4vy.atlassian.net/browse/TA-2332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: cdn version

- .trivyignore
- yarn.lock
> fix: ignore/upgrade dev dependencies

- packages/embed/src/types.ts
Adds `badgeBackground` to theme.
> feat: add badgeBackgorund to theme

- .trivyignore
> chore: update trivy deps

- .trivyignore
- packages/embed/src/form/form.ts
- packages/embed/src/subjects.ts
- yarn.lock
> feat: add support for push payments

- package.json
- yarn.lock
Updates auto to latest version (the release currently fails)
> deps: update auto

- apps/example-cdn/package.json
- apps/example-cjs/package.json
- apps/example-esm/package.json
- packages/embed-cdn/package.json
- packages/embed-react/package.json
- packages/embed/package.json
The last release pushed to NPM but due to branch protections were not pushed back to the repo. I have changed these protections so the next release should be successful.
https://gr4vy.atlassian.net/browse/TA-6974
> fix: update version numbers to match npm

- .github/workflows/ci.yml
- .trivyignore
- cloudbuild/cloudbuild-cdn.yaml
- package.json
- yarn.lock
Upgrades `lerna` to v8, which also helps fixing vulnerabilities that we previously ignored or solved with yarn resolutions.
**Ticket:** https://gr4vy.atlassian.net/browse/TA-6352
> task: upgrade to lerna v8

- packages/embed/src/index.ts
Send any `beforeTransactionError` error data to embed-ui, so it can be exposed in the `onEvent - transactionFailed` log info.
**Ticket:** https://gr4vy.atlassian.net/browse/TA-7168
> task: improve error logs

- packages/embed/src/types.ts
- packages/embed/src/validation.test.ts
- packages/embed/src/validation.ts
Adds support to the new `preselect` store option.
<sub>relates to https://github.com/gr4vy/embed-ui/pull/1216</sub>
> feat: add preselect store option

- packages/embed-react/dev/index.tsx
While testing with the local React dev app, I've noticed it was incomplete (no submit button, passing a dummy token, etc) making it unusable.
This PR adds the necessary code to make it work, also using the same defaults as the current [SDK one](https://github.com/gr4vy/gr4vy-embed/blob/main/packages/embed/dev/index.ts).
> chore: update react dev app to mimic the standard SDK one

- CONTRIBUTING.md
Adds EAA compliance section covering [WCAG 2.1](https://www.w3.org/TR/WCAG21/) Level AA and [EN 301-549](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf) standards, testing tools (axe-core, vitest-axe), and developer guidelines. Links to internal [Web Accessibility](https://gr4vy.atlassian.net/wiki/spaces/GB/pages/1410727952/Web+Accessibility) docs and [Frontend Coding Standards](https://gr4vy.atlassian.net/wiki/spaces/GB/pages/253657097/Frontend+Coding+Standards#Accessibility-ASSESS).
**Ticket: TA-11362**
> docs: add accessibility section to CONTRIBUTING
